# Generated by Django 4.2.2 on 2023-06-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0002_alter_activationlink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationlink',
            name='link',
            field=models.TextField(default='youjustmadeamistake'),
        ),
    ]
