# Generated by Django 4.2.2 on 2023-06-19 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_alter_clubjoinrequest_picture_alter_manager_picture_and_more'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPOV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='control.club')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='control.club')),
            ],
            options={
                'verbose_name': 'Match POV',
                'verbose_name_plural': 'Match POV',
            },
        ),
    ]
