# Generated by Django 4.2.2 on 2023-06-19 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_alter_clubjoinrequest_picture_alter_manager_picture_and_more'),
        ('stats', '0002_matchpov'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStartTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='matchpov',
            name='goal_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchpov',
            name='goal_for',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TeamStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('drew', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('x_factor', models.IntegerField(default=0)),
                ('rank_decider', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.club')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.BooleanField(default=False)),
                ('match_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.matchday')),
                ('match_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.matchstarttime')),
                ('match_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.matchpov')),
            ],
        ),
    ]
