# Generated by Django 4.2.2 on 2023-06-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_teamstat_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='forfeited',
            field=models.BooleanField(default=False),
        ),
    ]
