# Generated by Django 5.0.7 on 2024-07-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('html_id', models.CharField(blank=True, max_length=256, null=True)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Copies',
            },
        ),
    ]
