# Generated by Django 4.2.2 on 2023-06-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_clubadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='picture',
            new_name='picture_url',
        ),
    ]
