# Generated by Django 4.2.2 on 2023-06-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_rename_picture_player_picture_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(max_length=556, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='kit_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='kit_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='picture_url',
            field=models.TextField(default='https://images.icps7.xyz/profile/default.jpg'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=556, null=True)),
                ('picture_url', models.TextField(default='https://images.icps7.xyz/profile/default.jpg')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.club')),
            ],
        ),
    ]
