# Generated by Django 4.2.2 on 2023-06-15 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0005_rename_active_switch_is_active_remove_player_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
