# Generated by Django 4.2.2 on 2023-06-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_remove_player_full_name_remove_player_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='kit_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='kit_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
