# Generated by Django 4.2.2 on 2023-06-17 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0010_clubgroup_clubjoinrequest_club_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubjoinrequest',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.picture'),
        ),
        migrations.AddField(
            model_name='manager',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.picture'),
        ),
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.picture'),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='control.club'),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='control.club'),
        ),
    ]
