# Generated by Django 4.2.2 on 2023-06-18 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('control', '0011_clubjoinrequest_picture_manager_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.picture'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.picture'),
        ),
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.picture'),
        ),
    ]
